language: node_js
node_js:
  - 8.12.0

addons:
  apt:
    packages:
      - imagemagick
      - latexmk
      - texlive
      - texlive-latex-extra

before_install:
  - rvm install 2.3.1

install:
  - npm install gulp
  - npm install
  - gem install jekyll
  - gem install html-proofer
  - ./_docs.sh depend

script:
  - gulp build
  - npm test

after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_REPO_SLUG == "certbot/website" ]]; then bash ./push-build.sh; fi'

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - NODE_ENV=production

sudo: required

notifications:
  email: false
  irc:
    channels:
      # This is set to a secure variable to prevent forks from sending
      # notifications. This value was created by installing
      # https://github.com/travis-ci/travis.rb and running
      # `travis encrypt "chat.freenode.net#certbot-devel"`.
      - secure: "m8jEd5hCZxGRK1xUnU7JIx8o/I/gZPlHNpFPZh9fJlHDe4yWnatLR9xqkpf3qerTXD1pSl0om4M+BYfOZCJVxUeb5PH1qyW6a3RyMi+siuUwJv6PbvveNmuDGD8gMCARzyuhB0jZx5QvDpTDaSiY5BDfr9nI5JcZJwq4ecSVoSUleGJK5Dx0ngmp5ERSXpZhBGJpVqz0VZ32j/dNGQdZlTlAJM18i6lQiYUK4lZTkwQ5YcBjSjWrZEfTCyGja7YH1tz5b6XyPONB2u4iqYEs9N+jKVZwX8kg5yLCxEt2C7phJwDufiLtLly3en6iVt1IB25AfIdiLIJWSj0LFCwRT/f96/z9ayzeBWtTK/Q1guKaYHzNodjzWxhLMESyg5BQ+LZQm0pWqRIyrV+UFvdbv6UnbGckfPw4MLfIf4+GUuTa3CxL9vuzQQw/8euZcWDCxw6f8bZpHyMRhiBCh64CI1D1CKoHX5/jTbQ5hnxjmr5vijOtZMJZNPuLjK0BdDoJUPE9JH0ngJ7hIHanaxbRYs4XzXUSY0ZipynW5M+XkfpJqbB1i29+96s6pThXDS09FHy5pwHqkGlNJs2YdBGWm3h1CSHa+tUUy5WtO9tns6HDGgGthAKcs5YA62kwGzNYldpt4c3JyLbUQ31ct04tJZ/H6/k5VUeUr82OYfRSumE="
    on_success: never
    use_notice: true
