language: node_js
node_js:
  - 4.4.0

addons:
  apt:
    packages:
      - texlive
      - texlive-latex-extra

before_install:
  - rvm install 2.2.1

install:
  - npm install gulp
  - npm install
  - gem install jekyll
  - gem install html-proofer
  - pip install virtualenv
  - ./_docs.sh depend

script:
  - gulp build
  - npm test

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - NODE_ENV=production

# Only build pushes to the master branch, PRs, and branches beginning with `test-`.
branches:
  only:
    - master
    - /^test-.*$/

sudo: required