language: node_js
node_js:
  - 4.4.0

addons:
  apt:
    packages:
      - texlive
      - texlive-latex-extra

before_install:
  -  'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_e5009b71da55_key -iv $encrypted_e5009b71da55_iv -in build_key.enc -out build_key -d; fi'
  - rvm install 2.2.2

install:
  - npm install gulp
  - npm install
  - gem install jekyll
  - gem install html-proofer
  - ./_docs.sh depend

script:
  - gulp build
  - npm test

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./push-build.sh; fi'

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - NODE_ENV=production

sudo: required
