language: node_js
dist: focal
node_js:
  - 8.12.0

addons:
  apt:
    packages:
      - gsfonts
      - imagemagick
      - latexmk
      - texlive
      - texlive-latex-extra

before_install:
  - rvm install 2.6.3

install:
  - npm install gulp
  - npm install
  - gem install jekyll
  - gem install html-proofer
  - ./_docs.sh depend

script:
  - gulp build
  - npm test

after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_REPO_SLUG == "certbot/website" ]]; then bash ./push-build.sh; fi'

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - NODE_ENV=production

sudo: required
