# Site settings
title: Certbot
email: certbot@eff.org
description: > # this means to ignore newlines until "baseurl:"
  Automatically enable HTTPS on your website with EFF's Certbot, deploying Let's Encrypt certificates.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://certbot.eff.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
- faq_entries
exclude:
- README.md
- package.json
- node_modules
- gulpfile.js
- vendor
- _docs
- _gulp
- deploy_key.enc
- deploy_key
keep_files:
- css
- js
- docs

# Build settings
markdown: kramdown
